// ============================================================================
// BackHaul Market Pulse — MOCK / PLACEHOLDER DATA MODULE
// ----------------------------------------------------------------------------
// ⚠️  IMPORTANT — READ BEFORE LAUNCH  ⚠️
// Every number generated by this file is SYNTHETIC. It is derived from a
// deterministic seeded pseudo-random function (not a real rate feed and not
// real BackHaul transaction history), purely so the UI has stable, realistic-
// looking numbers to render during development.
//
// Do NOT present this data to paying customers as real market intelligence.
// Before charging anyone for Market Pulse, either:
//   1) Replace this module with a real licensed rate-data provider feed, or
//   2) Clearly label the feature "Preview" / "Demo" in the UI until you do.
//
// The two hardcoded LANE_OVERRIDES below exist only to match the worked
// example in the product spec (Atlanta -> Orlando ~$2.65/mi "Strong",
// Orlando -> Atlanta ~$2.25/mi) so the demo reliably shows that scenario.
// ============================================================================

export const EQUIPMENT_TYPES = [
  { key: "van", label: "Dry Van" },
  { key: "reefer", label: "Reefer" },
  { key: "flatbed", label: "Flatbed" },
  { key: "boxTruck", label: "Box Truck" },
  { key: "hotshot", label: "Hotshot" },
];

export const TIER_META = {
  hot: { label: "Hot", color: "#f97316", range: "$3.00+" },
  strong: { label: "Strong", color: "#eab308", range: "$2.50–$2.99" },
  average: { label: "Average", color: "#3b82f6", range: "$2.00–$2.49" },
  cool: { label: "Cool", color: "#64748b", range: "under $2.00" },
};

const EQUIPMENT_SPREAD = {
  van: 0,
  reefer: 0.35,
  flatbed: 0.2,
  boxTruck: -0.15,
  hotshot: 0.1,
};

const DEMAND_BASE = { High: 2.55, Medium: 2.15, Low: 1.85 };

// ---- deterministic seeded "random" helpers (stable across re-renders) -----
function seededRandom(seedStr) {
  let h = 0;
  for (let i = 0; i < seedStr.length; i++) {
    h = (h << 5) - h + seedStr.charCodeAt(i);
    h |= 0;
  }
  const x = Math.sin(h) * 10000;
  return x - Math.floor(x);
}
function seededRange(seedStr, min, max) {
  return min + seededRandom(seedStr) * (max - min);
}
function round2(n) {
  return Math.round(n * 100) / 100;
}

function rateTier(rate) {
  if (rate >= 3.0) return "hot";
  if (rate >= 2.5) return "strong";
  if (rate >= 2.0) return "average";
  return "cool";
}

function confidenceFromCount(count) {
  if (count >= 40) return "High";
  if (count >= 15) return "Medium";
  return "Low";
}

function haversineMiles(lat1, lng1, lat2, lng2) {
  const R = 3958.8;
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c) || 1;
}

// ---- Southeast MVP markets --------------------------------------------------
const MARKETS_RAW = [
  { slug: "atlanta-ga", name: "Atlanta", state: "GA", lat: 33.749, lng: -84.388, demand: "High" },
  { slug: "orlando-fl", name: "Orlando", state: "FL", lat: 28.538, lng: -81.379, demand: "High" },
  { slug: "charlotte-nc", name: "Charlotte", state: "NC", lat: 35.227, lng: -80.843, demand: "High" },
  { slug: "nashville-tn", name: "Nashville", state: "TN", lat: 36.163, lng: -86.781, demand: "Medium" },
  { slug: "memphis-tn", name: "Memphis", state: "TN", lat: 35.150, lng: -90.049, demand: "High" },
  { slug: "jacksonville-fl", name: "Jacksonville", state: "FL", lat: 30.332, lng: -81.656, demand: "Medium" },
  { slug: "tampa-fl", name: "Tampa", state: "FL", lat: 27.951, lng: -82.457, demand: "Medium" },
  { slug: "miami-fl", name: "Miami", state: "FL", lat: 25.762, lng: -80.192, demand: "High" },
  { slug: "birmingham-al", name: "Birmingham", state: "AL", lat: 33.521, lng: -86.802, demand: "Medium" },
  { slug: "savannah-ga", name: "Savannah", state: "GA", lat: 32.081, lng: -81.091, demand: "High" },
  { slug: "columbia-sc", name: "Columbia", state: "SC", lat: 34.001, lng: -81.035, demand: "Medium" },
  { slug: "charleston-sc", name: "Charleston", state: "SC", lat: 32.777, lng: -79.931, demand: "Medium" },
  { slug: "raleigh-nc", name: "Raleigh", state: "NC", lat: 35.780, lng: -78.639, demand: "Medium" },
  { slug: "knoxville-tn", name: "Knoxville", state: "TN", lat: 35.960, lng: -83.921, demand: "Low" },
  { slug: "chattanooga-tn", name: "Chattanooga", state: "TN", lat: 35.045, lng: -85.310, demand: "Medium" },
  { slug: "greenville-sc", name: "Greenville", state: "SC", lat: 34.852, lng: -82.394, demand: "Medium" },
  { slug: "montgomery-al", name: "Montgomery", state: "AL", lat: 32.367, lng: -86.300, demand: "Low" },
  { slug: "huntsville-al", name: "Huntsville", state: "AL", lat: 34.730, lng: -86.586, demand: "Low" },
  { slug: "greensboro-nc", name: "Greensboro", state: "NC", lat: 36.073, lng: -79.792, demand: "Medium" },
  { slug: "columbus-ga", name: "Columbus", state: "GA", lat: 32.461, lng: -84.988, demand: "Low" },
];

function buildEquipmentStats(marketSlug, demand) {
  const base = DEMAND_BASE[demand] || DEMAND_BASE.Medium;
  const stats = {};
  EQUIPMENT_TYPES.forEach(({ key }) => {
    const seed = `${marketSlug}-${key}`;
    const marketEstimate = Math.max(
      1.2,
      base + EQUIPMENT_SPREAD[key] + seededRange(seed + "-est", -0.25, 0.35)
    );
    const verifiedAvg = Math.max(
      1.1,
      marketEstimate + seededRange(seed + "-ver", -0.15, 0.2)
    );
    const transactionCount = Math.round(seededRange(seed + "-count", 8, 65));
    const minutesAgo = Math.round(seededRange(seed + "-time", 4, 240));
    stats[key] = {
      marketEstimate: round2(marketEstimate),
      verifiedAvg: round2(verifiedAvg),
      transactionCount,
      confidence: confidenceFromCount(transactionCount),
      tier: rateTier(verifiedAvg),
      minutesAgo,
    };
  });
  return stats;
}

export const MARKETS = MARKETS_RAW.map((m) => ({
  ...m,
  equipment: buildEquipmentStats(m.slug, m.demand),
}));

export function findMarket(slug) {
  return MARKETS.find((m) => m.slug === slug) || null;
}

export function nearestMarket(lat, lng) {
  let best = null;
  let bestDist = Infinity;
  MARKETS.forEach((m) => {
    const d = haversineMiles(lat, lng, m.lat, m.lng);
    if (d < bestDist) {
      bestDist = d;
      best = m;
    }
  });
  if (!best || bestDist > 120) return null;
  return { market: best, distanceMiles: bestDist };
}

// Hardcoded so the product-spec worked example always renders exactly as
// described: Atlanta -> Orlando ~$2.65/mi (Strong), Orlando -> Atlanta
// ~$2.25/mi (Average) on dry van. Every other lane is generated.
const LANE_OVERRIDES = {
  "atlanta-ga->orlando-fl": { van: 2.65 },
  "orlando-fl->atlanta-ga": { van: 2.25 },
};

function laneRate(originSlug, destSlug, equipmentKey, miles) {
  const seed = `${originSlug}->${destSlug}-${equipmentKey}`;
  const base = 2.2 + (EQUIPMENT_SPREAD[equipmentKey] || 0);
  const distanceFactor = miles > 500 ? -0.15 : miles < 150 ? 0.25 : 0;
  const variance = seededRange(seed, -0.3, 0.3);
  return Math.max(1.1, round2(base + distanceFactor + variance));
}

function buildLane(origin, dest) {
  const miles = haversineMiles(origin.lat, origin.lng, dest.lat, dest.lng);
  const overrideKey = `${origin.slug}->${dest.slug}`;
  const overrides = LANE_OVERRIDES[overrideKey] || {};
  const rates = {};
  EQUIPMENT_TYPES.forEach(({ key }) => {
    rates[key] =
      overrides[key] !== undefined
        ? overrides[key]
        : laneRate(origin.slug, dest.slug, key, miles);
  });
  return {
    originSlug: origin.slug,
    originName: `${origin.name}, ${origin.state}`,
    destinationSlug: dest.slug,
    destinationName: `${dest.name}, ${dest.state}`,
    miles,
    tier: rateTier(rates.van),
    ...rates,
  };
}

export function lanesFromMarket(slug, count = 5) {
  const origin = findMarket(slug);
  if (!origin) return [];
  const ranked = MARKETS.filter((m) => m.slug !== slug)
    .map((m) => ({ m, weight: seededRandom(`${slug}-rank-${m.slug}`) }))
    .sort((a, b) => b.weight - a.weight)
    .slice(0, count)
    .map(({ m }) => m);
  return ranked.map((dest) => buildLane(origin, dest));
}

export function lanesBetween(originSlug, destSlug) {
  const origin = findMarket(originSlug);
  const dest = findMarket(destSlug);
  if (!origin || !dest) return null;
  const outboundLane = buildLane(origin, dest);
  const inboundLane = buildLane(dest, origin);
  const outboundCount = Math.round(
    seededRange(`${originSlug}->${destSlug}-txcount`, 10, 60)
  );
  return {
    originName: outboundLane.originName,
    destinationName: outboundLane.destinationName,
    miles: outboundLane.miles,
    outbound: {
      van: outboundLane.van,
      transactionCount: outboundCount,
      confidence: confidenceFromCount(outboundCount),
      tier: outboundLane.tier,
    },
    inbound: {
      van: inboundLane.van,
    },
  };
}

export function formatMinutesAgo(minutes) {
  if (minutes < 60) return `${minutes} min ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours} hr${hours === 1 ? "" : "s"} ago`;
  const days = Math.round(hours / 24);
  return `${days} day${days === 1 ? "" : "s"} ago`;
}
