// ============================================================================
// BackHaul Market Pulse — MOCK / PLACEHOLDER DATA MODULE
// ----------------------------------------------------------------------------
// ⚠️  IMPORTANT — READ BEFORE LAUNCH  ⚠️
// Every number generated by this file is SYNTHETIC. It is derived from a
// deterministic seeded pseudo-random function (not a real rate feed and not
// real BackHaul transaction history), purely so the UI has stable, realistic-
// looking numbers to render during development. This now covers markets
// nationwide, but the data itself is still 100% placeholder everywhere.
//
// Do NOT present this data to paying customers as real market intelligence.
// Before charging anyone for Market Pulse, either:
//   1) Replace this module with a real licensed rate-data provider feed, and/
//      or a real "confirmed load" capture flow for the BackHaul-verified side, or
//   2) Clearly label the feature "Preview" / "Demo" in the UI until you do
//      (the page currently does this).
//
// The two hardcoded LANE_OVERRIDES below exist only to match the worked
// example in the product spec (Atlanta -> Orlando ~$2.65/mi "Strong",
// Orlando -> Atlanta ~$2.25/mi) so the demo reliably shows that scenario.
// ============================================================================

export const EQUIPMENT_TYPES = [
  { key: "van", label: "Dry Van" },
  { key: "reefer", label: "Reefer" },
  { key: "flatbed", label: "Flatbed" },
  { key: "boxTruck", label: "Box Truck" },
  { key: "hotshot", label: "Hotshot" },
];

export const TIER_META = {
  hot: { label: "Hot", color: "#f97316", range: "$3.00+" },
  strong: { label: "Strong", color: "#eab308", range: "$2.50–$2.99" },
  average: { label: "Average", color: "#3b82f6", range: "$2.00–$2.49" },
  cool: { label: "Cool", color: "#64748b", range: "under $2.00" },
};

const EQUIPMENT_SPREAD = {
  van: 0,
  reefer: 0.35,
  flatbed: 0.2,
  boxTruck: -0.15,
  hotshot: 0.1,
};

const DEMAND_BASE = { High: 2.55, Medium: 2.15, Low: 1.85 };

// ---- deterministic seeded "random" helpers (stable across re-renders) -----
function seededRandom(seedStr) {
  let h = 0;
  for (let i = 0; i < seedStr.length; i++) {
    h = (h << 5) - h + seedStr.charCodeAt(i);
    h |= 0;
  }
  const x = Math.sin(h) * 10000;
  return x - Math.floor(x);
}
function seededRange(seedStr, min, max) {
  return min + seededRandom(seedStr) * (max - min);
}
function round2(n) {
  return Math.round(n * 100) / 100;
}

function rateTier(rate) {
  if (rate >= 3.0) return "hot";
  if (rate >= 2.5) return "strong";
  if (rate >= 2.0) return "average";
  return "cool";
}

function confidenceFromCount(count) {
  if (count >= 40) return "High";
  if (count >= 15) return "Medium";
  return "Low";
}

function haversineMiles(lat1, lng1, lat2, lng2) {
  const R = 3958.8;
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c) || 1;
}

// ---- Nationwide markets (preview) ------------------------------------------
// Originally launched as a 20-city Southeast MVP; expanded to cover major
// freight hubs across every region of the continental US. The first 20
// entries are the original Southeast set (kept as-is so existing lane
// overrides / slugs don't change).
const MARKETS_RAW = [
  // --- Southeast (original MVP set) ---
  { slug: "atlanta-ga", name: "Atlanta", state: "GA", lat: 33.749, lng: -84.388, demand: "High" },
  { slug: "orlando-fl", name: "Orlando", state: "FL", lat: 28.538, lng: -81.379, demand: "High" },
  { slug: "charlotte-nc", name: "Charlotte", state: "NC", lat: 35.227, lng: -80.843, demand: "High" },
  { slug: "nashville-tn", name: "Nashville", state: "TN", lat: 36.163, lng: -86.781, demand: "Medium" },
  { slug: "memphis-tn", name: "Memphis", state: "TN", lat: 35.150, lng: -90.049, demand: "High" },
  { slug: "jacksonville-fl", name: "Jacksonville", state: "FL", lat: 30.332, lng: -81.656, demand: "Medium" },
  { slug: "tampa-fl", name: "Tampa", state: "FL", lat: 27.951, lng: -82.457, demand: "Medium" },
  { slug: "miami-fl", name: "Miami", state: "FL", lat: 25.762, lng: -80.192, demand: "High" },
  { slug: "birmingham-al", name: "Birmingham", state: "AL", lat: 33.521, lng: -86.802, demand: "Medium" },
  { slug: "savannah-ga", name: "Savannah", state: "GA", lat: 32.081, lng: -81.091, demand: "High" },
  { slug: "columbia-sc", name: "Columbia", state: "SC", lat: 34.001, lng: -81.035, demand: "Medium" },
  { slug: "charleston-sc", name: "Charleston", state: "SC", lat: 32.777, lng: -79.931, demand: "Medium" },
  { slug: "raleigh-nc", name: "Raleigh", state: "NC", lat: 35.780, lng: -78.639, demand: "Medium" },
  { slug: "knoxville-tn", name: "Knoxville", state: "TN", lat: 35.960, lng: -83.921, demand: "Low" },
  { slug: "chattanooga-tn", name: "Chattanooga", state: "TN", lat: 35.045, lng: -85.310, demand: "Medium" },
  { slug: "greenville-sc", name: "Greenville", state: "SC", lat: 34.852, lng: -82.394, demand: "Medium" },
  { slug: "montgomery-al", name: "Montgomery", state: "AL", lat: 32.367, lng: -86.300, demand: "Low" },
  { slug: "huntsville-al", name: "Huntsville", state: "AL", lat: 34.730, lng: -86.586, demand: "Low" },
  { slug: "greensboro-nc", name: "Greensboro", state: "NC", lat: 36.073, lng: -79.792, demand: "Medium" },
  { slug: "columbus-ga", name: "Columbus", state: "GA", lat: 32.461, lng: -84.988, demand: "Low" },

  // --- Northeast / Mid-Atlantic ---
  { slug: "new-york-ny", name: "New York", state: "NY", lat: 40.713, lng: -74.006, demand: "High" },
  { slug: "newark-nj", name: "Newark", state: "NJ", lat: 40.735, lng: -74.172, demand: "High" },
  { slug: "philadelphia-pa", name: "Philadelphia", state: "PA", lat: 39.952, lng: -75.165, demand: "High" },
  { slug: "pittsburgh-pa", name: "Pittsburgh", state: "PA", lat: 40.440, lng: -79.996, demand: "Medium" },
  { slug: "boston-ma", name: "Boston", state: "MA", lat: 42.361, lng: -71.058, demand: "High" },
  { slug: "baltimore-md", name: "Baltimore", state: "MD", lat: 39.290, lng: -76.612, demand: "Medium" },
  { slug: "washington-dc", name: "Washington", state: "DC", lat: 38.907, lng: -77.037, demand: "Medium" },
  { slug: "buffalo-ny", name: "Buffalo", state: "NY", lat: 42.886, lng: -78.878, demand: "Low" },
  { slug: "harrisburg-pa", name: "Harrisburg", state: "PA", lat: 40.273, lng: -76.886, demand: "Medium" },
  { slug: "allentown-pa", name: "Allentown", state: "PA", lat: 40.608, lng: -75.490, demand: "Medium" },

  // --- Midwest ---
  { slug: "chicago-il", name: "Chicago", state: "IL", lat: 41.878, lng: -87.630, demand: "High" },
  { slug: "indianapolis-in", name: "Indianapolis", state: "IN", lat: 39.768, lng: -86.158, demand: "High" },
  { slug: "columbus-oh", name: "Columbus", state: "OH", lat: 39.961, lng: -82.999, demand: "High" },
  { slug: "cleveland-oh", name: "Cleveland", state: "OH", lat: 41.499, lng: -81.694, demand: "Medium" },
  { slug: "cincinnati-oh", name: "Cincinnati", state: "OH", lat: 39.103, lng: -84.512, demand: "High" },
  { slug: "detroit-mi", name: "Detroit", state: "MI", lat: 42.331, lng: -83.046, demand: "Medium" },
  { slug: "grand-rapids-mi", name: "Grand Rapids", state: "MI", lat: 42.963, lng: -85.668, demand: "Low" },
  { slug: "milwaukee-wi", name: "Milwaukee", state: "WI", lat: 43.039, lng: -87.906, demand: "Medium" },
  { slug: "minneapolis-mn", name: "Minneapolis", state: "MN", lat: 44.978, lng: -93.265, demand: "Medium" },
  { slug: "st-louis-mo", name: "St. Louis", state: "MO", lat: 38.627, lng: -90.199, demand: "High" },
  { slug: "kansas-city-mo", name: "Kansas City", state: "MO", lat: 39.099, lng: -94.578, demand: "High" },
  { slug: "des-moines-ia", name: "Des Moines", state: "IA", lat: 41.586, lng: -93.625, demand: "Low" },
  { slug: "omaha-ne", name: "Omaha", state: "NE", lat: 41.257, lng: -95.995, demand: "Medium" },
  { slug: "louisville-ky", name: "Louisville", state: "KY", lat: 38.253, lng: -85.759, demand: "High" },

  // --- South / South Central ---
  { slug: "dallas-tx", name: "Dallas", state: "TX", lat: 32.777, lng: -96.797, demand: "High" },
  { slug: "fort-worth-tx", name: "Fort Worth", state: "TX", lat: 32.755, lng: -97.330, demand: "High" },
  { slug: "houston-tx", name: "Houston", state: "TX", lat: 29.760, lng: -95.370, demand: "High" },
  { slug: "san-antonio-tx", name: "San Antonio", state: "TX", lat: 29.424, lng: -98.494, demand: "Medium" },
  { slug: "austin-tx", name: "Austin", state: "TX", lat: 30.267, lng: -97.743, demand: "Medium" },
  { slug: "oklahoma-city-ok", name: "Oklahoma City", state: "OK", lat: 35.468, lng: -97.516, demand: "Medium" },
  { slug: "tulsa-ok", name: "Tulsa", state: "OK", lat: 36.154, lng: -95.993, demand: "Low" },
  { slug: "new-orleans-la", name: "New Orleans", state: "LA", lat: 29.951, lng: -90.072, demand: "Medium" },
  { slug: "baton-rouge-la", name: "Baton Rouge", state: "LA", lat: 30.451, lng: -91.187, demand: "Medium" },
  { slug: "little-rock-ar", name: "Little Rock", state: "AR", lat: 34.746, lng: -92.290, demand: "Low" },
  { slug: "shreveport-la", name: "Shreveport", state: "LA", lat: 32.525, lng: -93.750, demand: "Low" },
  { slug: "jackson-ms", name: "Jackson", state: "MS", lat: 32.299, lng: -90.185, demand: "Low" },

  // --- Mountain / Southwest ---
  { slug: "denver-co", name: "Denver", state: "CO", lat: 39.739, lng: -104.990, demand: "High" },
  { slug: "phoenix-az", name: "Phoenix", state: "AZ", lat: 33.448, lng: -112.074, demand: "High" },
  { slug: "tucson-az", name: "Tucson", state: "AZ", lat: 32.222, lng: -110.926, demand: "Low" },
  { slug: "albuquerque-nm", name: "Albuquerque", state: "NM", lat: 35.084, lng: -106.651, demand: "Medium" },
  { slug: "el-paso-tx", name: "El Paso", state: "TX", lat: 31.759, lng: -106.487, demand: "Medium" },
  { slug: "salt-lake-city-ut", name: "Salt Lake City", state: "UT", lat: 40.760, lng: -111.891, demand: "Medium" },
  { slug: "las-vegas-nv", name: "Las Vegas", state: "NV", lat: 36.169, lng: -115.140, demand: "Medium" },
  { slug: "colorado-springs-co", name: "Colorado Springs", state: "CO", lat: 38.834, lng: -104.821, demand: "Low" },
  { slug: "boise-id", name: "Boise", state: "ID", lat: 43.615, lng: -116.202, demand: "Low" },

  // --- West Coast / Pacific Northwest ---
  { slug: "los-angeles-ca", name: "Los Angeles", state: "CA", lat: 34.052, lng: -118.244, demand: "High" },
  { slug: "long-beach-ca", name: "Long Beach", state: "CA", lat: 33.767, lng: -118.190, demand: "High" },
  { slug: "san-diego-ca", name: "San Diego", state: "CA", lat: 32.716, lng: -117.161, demand: "Medium" },
  { slug: "san-francisco-ca", name: "San Francisco", state: "CA", lat: 37.775, lng: -122.419, demand: "Medium" },
  { slug: "oakland-ca", name: "Oakland", state: "CA", lat: 37.804, lng: -122.271, demand: "High" },
  { slug: "sacramento-ca", name: "Sacramento", state: "CA", lat: 38.582, lng: -121.494, demand: "Medium" },
  { slug: "fresno-ca", name: "Fresno", state: "CA", lat: 36.747, lng: -119.772, demand: "Medium" },
  { slug: "portland-or", name: "Portland", state: "OR", lat: 45.515, lng: -122.679, demand: "Medium" },
  { slug: "seattle-wa", name: "Seattle", state: "WA", lat: 47.606, lng: -122.332, demand: "High" },
  { slug: "spokane-wa", name: "Spokane", state: "WA", lat: 47.658, lng: -117.426, demand: "Low" },
];

function buildEquipmentStats(marketSlug, demand) {
  const base = DEMAND_BASE[demand] || DEMAND_BASE.Medium;
  const stats = {};
  EQUIPMENT_TYPES.forEach(({ key }) => {
    const seed = `${marketSlug}-${key}`;
    const marketEstimate = Math.max(
      1.2,
      base + EQUIPMENT_SPREAD[key] + seededRange(seed + "-est", -0.25, 0.35)
    );
    const verifiedAvg = Math.max(
      1.1,
      marketEstimate + seededRange(seed + "-ver", -0.15, 0.2)
    );
    const transactionCount = Math.round(seededRange(seed + "-count", 8, 65));
    const minutesAgo = Math.round(seededRange(seed + "-time", 4, 240));
    stats[key] = {
      marketEstimate: round2(marketEstimate),
      verifiedAvg: round2(verifiedAvg),
      transactionCount,
      confidence: confidenceFromCount(transactionCount),
      tier: rateTier(verifiedAvg),
      minutesAgo,
    };
  });
  return stats;
}

export const MARKETS = MARKETS_RAW.map((m) => ({
  ...m,
  equipment: buildEquipmentStats(m.slug, m.demand),
}));

export function findMarket(slug) {
  return MARKETS.find((m) => m.slug === slug) || null;
}

// Nationwide coverage has bigger gaps between markets than the old Southeast
// set did, so the "nearby market" radius is wider than before (was 120mi).
const NEAREST_MARKET_RADIUS_MILES = 175;

export function nearestMarket(lat, lng) {
  let best = null;
  let bestDist = Infinity;
  MARKETS.forEach((m) => {
    const d = haversineMiles(lat, lng, m.lat, m.lng);
    if (d < bestDist) {
      bestDist = d;
      best = m;
    }
  });
  if (!best || bestDist > NEAREST_MARKET_RADIUS_MILES) return null;
  return { market: best, distanceMiles: bestDist };
}

// Hardcoded so the product-spec worked example always renders exactly as
// described: Atlanta -> Orlando ~$2.65/mi (Strong), Orlando -> Atlanta
// ~$2.25/mi (Average) on dry van. Every other lane is generated.
const LANE_OVERRIDES = {
  "atlanta-ga->orlando-fl": { van: 2.65 },
  "orlando-fl->atlanta-ga": { van: 2.25 },
};

function laneRate(originSlug, destSlug, equipmentKey, miles) {
  const seed = `${originSlug}->${destSlug}-${equipmentKey}`;
  const base = 2.2 + (EQUIPMENT_SPREAD[equipmentKey] || 0);
  const distanceFactor = miles > 500 ? -0.15 : miles < 150 ? 0.25 : 0;
  const variance = seededRange(seed, -0.3, 0.3);
  return Math.max(1.1, round2(base + distanceFactor + variance));
}

function buildLane(origin, dest) {
  const miles = haversineMiles(origin.lat, origin.lng, dest.lat, dest.lng);
  const overrideKey = `${origin.slug}->${dest.slug}`;
  const overrides = LANE_OVERRIDES[overrideKey] || {};
  const rates = {};
  EQUIPMENT_TYPES.forEach(({ key }) => {
    rates[key] =
      overrides[key] !== undefined
        ? overrides[key]
        : laneRate(origin.slug, dest.slug, key, miles);
  });
  return {
    originSlug: origin.slug,
    originName: `${origin.name}, ${origin.state}`,
    destinationSlug: dest.slug,
    destinationName: `${dest.name}, ${dest.state}`,
    miles,
    tier: rateTier(rates.van),
    ...rates,
  };
}

export function lanesFromMarket(slug, count = 5) {
  const origin = findMarket(slug);
  if (!origin) return [];
  const ranked = MARKETS.filter((m) => m.slug !== slug)
    .map((m) => ({ m, weight: seededRandom(`${slug}-rank-${m.slug}`) }))
    .sort((a, b) => b.weight - a.weight)
    .slice(0, count)
    .map(({ m }) => m);
  return ranked.map((dest) => buildLane(origin, dest));
}

export function lanesBetween(originSlug, destSlug) {
  const origin = findMarket(originSlug);
  const dest = findMarket(destSlug);
  if (!origin || !dest) return null;
  const outboundLane = buildLane(origin, dest);
  const inboundLane = buildLane(dest, origin);
  const outboundCount = Math.round(
    seededRange(`${originSlug}->${destSlug}-txcount`, 10, 60)
  );
  return {
    originName: outboundLane.originName,
    destinationName: outboundLane.destinationName,
    miles: outboundLane.miles,
    outbound: {
      van: outboundLane.van,
      transactionCount: outboundCount,
      confidence: confidenceFromCount(outboundCount),
      tier: outboundLane.tier,
    },
    inbound: {
      van: inboundLane.van,
    },
  };
}

export function formatMinutesAgo(minutes) {
  if (minutes < 60) return `${minutes} min ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours} hr${hours === 1 ? "" : "s"} ago`;
  const days = Math.round(hours / 24);
  return `${days} day${days === 1 ? "" : "s"} ago`;
}
